# permissions for end users to edit testapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ty-case
    app.kubernetes.io/part-of: ty-case
    app.kubernetes.io/managed-by: kustomize
  name: testapp-editor-role
rules:
- apiGroups:
  - apps.test.com
  resources:
  - testapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.test.com
  resources:
  - testapps/status
  verbs:
  - get
